### PR TITLE
Issue 61

### PR DESCRIPTION
**Pull request by Serthys**
Solves the issue with #61.

### CODE REVIEW

**Review by bzuillsmith — COMMENTED** [review]
Why is this commit removing the rotation you added?

**Comment by Serthys** [comment]
I'm not sure since it's almost 2 years old already, but `dist` folder where the edits were done is now gone anyway. I guess I should justclose it.

**Comment by Serthys** [comment]
Ah I think I know waht happener. Those were probably some old changes I had and I forgot to remove them before uploading the fix. The only relevant commit should be 18029b1dd0cdf2acc09e976a1be09c6cbc1536a2.

**Comment by bzuillsmith** [comment]
Yeah, sorry, I haven't put hardly any time into this project for the last 2 years or so. One of these commits fixes a webpack dependency issue though.

**Comment by Serthys** [comment]
I'll create a new branch with only the relevant changes.

**Pull request closed without merging**
